@Bot.command()
@commands.has_permissions(view_audit_log=True)
async def mute(ctx,member:discord.Member,time:int,reason):
    role = discord.utils.get(ctx.guild.roles,id=ВашАйди)
    channel = Bot.get_channel(ВашАйди)
    await member.add_roles(role)
    emb = discord.Embed(title="Мут",color=0x2f3136)
    emb.add_field(name='Модератор',value=ctx.message.author.mention,inline=False)
    emb.add_field(name='Нарушитель',value=member.mention,inline=False)
    emb.add_field(name='Причина',value=reason,inline=False)
    emb.add_field(name="Время",value=time,inline=False)
    await channel.send(embed = emb)
    await asyncio.sleep(time*60 )
    emb = discord.Embed(title="Анмут",color=0x2f3136)
    emb.add_field(name='Модератор',value='<@709725675711496233>',inline=False)
    emb.add_field(name='Нарушитель',value=member.mention,inline=False)
    emb.add_field(name='Причина',value="Время мута вышло",inline=False)
    await channel.send(embed=emb)
    await member.remove_roles(role)
@Bot.command()
@commands.has_permissions(view_audit_log=True)
async def unmute(ctx,member:discord.Member):
    channel = Bot.get_channel(ВашАйди)
    muterole = discord.utils.get(ctx.guild.roles,id=ВашАйди)
    emb = discord.Embed(title="Анмут",color=0xff0000)
    emb.add_field(name='Модератор',value=ctx.message.author.mention,inline=False)
    emb.add_field(name='Нарушитель',value=member.mention,inline=False)
    await channel.send(embed = emb)
    await member.remove_roles(muterole)
@Bot.command()
@commands.has_permissions(view_audit_log=True)
async def kick(ctx,member:discord.Member,reason):
    channel = Bot.get_channel(ВашАйди)
    emb = discord.Embed(title="Кик",color=0xff0000)
    emb.add_field(name='Модератор',value=ctx.message.author.mention,inline=False)
    emb.add_field(name='Нарушитель',value=member.mention,inline=False)
    emb.add_field(name='Причина',value=reason,inline=False)
    await member.kick()
    await channel.send(embed = emb)
@Bot.command()
@commands.has_permissions(view_audit_log=True)
async def ban(ctx,member:discord.Member,reason):
    channel = Bot.get_channel(ВашАйди)
    emb = discord.Embed(title="Кик",color=0xff0000)
    emb.add_field(name='Модератор',value=ctx.message.author.mention,inline=False)
    emb.add_field(name='Нарушитель',value=member.mention,inline=False)
    emb.add_field(name='Причина',value=reason,inline=False)
    await member.ban()
    await channel.send(embed = emb)
@Bot.command()
@commands.has_permissions(view_audit_log=True)
async def clear(ctx,amount=10):
    await ctx.message.channel.purge(limit=amount + 1)